export * from './HeroSection';
export * from './WhyKhamsaSection';
export * from './PhilosophySection';
export * from './ServicesSection';
export * from './PlatformLearningSection';
export * from './FounderSection';
export * from './QuoteSection';
export * from './SocialCtaSection';
export * from './FinalCtaSection';
